server:
  port: 8080

spring:
  application:
    name: homework-manegement
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/homework_management?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

mybatis-plus:
  type-aliases-package: com.java.homeworkmanagement.pojo
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ¥Ú”°sql
logging:
  level:
    com.java.homeworkmanagement.dao: debug
